# Neo4j Database Configuration
neo4j:
  host: localhost
  port: 7687
  user: neo4j
  password: password

base:
  dir: /home/lin/work/code/DeepLearning/LLM/Medical

save:
  dir: save

knowledge:
  dir: data/knowledge/knowledge.json

graph:
  dir: data/graph/graph.json

faiss:
  faiss_index_path: data/faiss_index/faiss_index.index
  metadata_path: data/faiss_index/matedata.npy

embedding:
  path: model/bge-large-zh-v1.5