# Neo4j Database Configuration
neo4j:
  host: localhost
  port: 7687
  user: neo4j
  password: password

base:
  dir: /home/lin/work/code/DeepLearning/LLM/Medical

save:
  dir: save

knowledge:
  dir: data/knowledge/test.json

graph:
  dir: graph/data.json
